dist: trusty
sudo: required

auth: &Auth |
  npm i -g travis-env && eval "$(travis-env)"
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build
      name: "Build latest tag"
      script:
        - *Auth
        - docker build . -t eventology/alpine-vips:latest
        - docker push eventology/alpine-vips:latest

stages:
  - build
