docker_login: &DockerLogin |
  echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin

version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: *DockerLogin
      - run: docker build . -t eventology/alpine-vips:latest
      - run: docker push eventology/alpine-vips:latest
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: master
